apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-service-db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service-db
  template:
    metadata:
      labels:
        app: app-service-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          envFrom:
            - configMapRef:
                name: app-config-map-db
            - secretRef:
                name: app-db-secrets
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 120m
              memory: 112Mi
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: db-pvc
